# Dependabot will run on day 25 of each month at 01:28 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      day: 23
      timezone: "Europe/Berlin"
      cronjob: "28 1 25 * *"
    open-pull-requests-limit: 15
    assignees:
      - "baeri_wiliwonka"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      day: 23
      timezone: "Europe/Berlin"
      cronjob: "28 1 25 * *"
    open-pull-requests-limit: 15
    assignees:
      - "baeri_wiliwonka"
